import Head from 'next/head';

export default function MyHead() {
    return (
        <Head>
            <meta content="width=device-width, initial-scale=1" name="viewport" />
            <meta name="description" content="Generated by create next app" />

            {/* Utilisation d'un chemin relatif pour le favicon */}
            <link rel="icon" type="image/x-icon" href="/favicon.ico" />

            {/* Préchargement de la feuille de style CSS */}
            <link rel="preload" href="/_next/static/css/app/layout.css?v=1691612824612" as="style" />

            {/* Lien vers la feuille de style CSS */}
            <link rel="stylesheet" href="/_next/static/css/app/layout.css?v=1691612824612" />
        </Head>
    );
}