import Head from 'next/head';

export default function MyHead() {
    return (
        <Head>
            <meta content="width=device-width, initial-scale=1" name="viewport" />
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" type="image/x-icon" href="/favicon.ico" />
        </Head>
    );
}